name: pushengage_flutter_sdk
description: PushEngage Flutter Plugin allows you to integrate Push Notification service into your Flutter application.

version: 0.0.1
homepage: https://github.com/awesomemotive/pushengage-flutter-sdk
repository: https://github.com/awesomemotive/pushengage-flutter-sdk

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pushengage.pushengage_flutter_sdk
        pluginClass: PushEngageFlutterSdkPlugin
      ios:
        pluginClass: PushEngageFlutterSdkPlugin
