/// A `custom`-type action button tap inside a displayed in-app message.
///
/// Delivered via [PushEngage.onIAMCustomAction]. The native SDKs handle
/// `open_url`, `dismiss`, and `request_notification_permission` action types
/// internally — only `custom` actions reach this stream.
class IAMCustomAction {
  /// The button's internal key (e.g. "t04B05"), generated by the dashboard.
  /// Do not route on it — use `parameters['action']`.
  final String actionId;

  /// Parameters attached to the action. `action` holds the button's "Action
  /// name" from the dashboard — route on that. Values are stringified by the
  /// native bridge, so mixed native payloads always arrive as strings.
  final Map<String, String> parameters;

  const IAMCustomAction({required this.actionId, required this.parameters});

  @override
  String toString() =>
      'IAMCustomAction(actionId: $actionId, parameters: $parameters)';
}
